spring.profiles: local

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/auto_diary?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      pool-name: hikari-cp
      maximum-pool-size: 20
      minimum-idle: 10
    sql-script-encoding: UTF-8

  redis:
    host: localhost
    port: 6379
    password: "#{null}"
    ssl: false
    cache_database: 0
    jedis:
      pool:
        max-active: 20
        max-idle: 8
        max-wait: 5000
        min-idle: 4
    timeout: 5000

logging:
  level:
    org.springframework: info
    io.solabs.autodiary: debug
  file:
    path: /servers/logs

open-ai:
  api-key: ""
  org-key: ""
